### ISSUE TITLE
Resources for service accounts and service account tokens

### ISSUE THREAD

**Issue by JonasBak** [Unleash/terraform-provider-unleash#125]
### Describe the feature request

I would like to be able to manage service accounts and tokens with terraform.

### Background

We manage a lot of stuff for a lot of teams through terraform, and we would like to automatically set up service accounts for different teams with terraform, and grant them permissions to the appropriate projects.

These would be used in each team's terraform workspaces, so they for example would be able to create client tokens through terraform and automatically inject them into where they are needed. This way we don't need to manually copy-paste tokens around and manually manage them.

I could look into implementing the resources myself, but I couldn't find support for it in the [client library](https://github.com/Unleash/unleash-server-api-go).

### Solution suggestions

Add `unleash_service_account` and `unleash_service_account_token` resources.

**Comment by gastonfournier** [comment]
I think this is a nice to have feature and because the APIs for users and service accounts are similar, we can re-use some of the code we have for users to implement this feature

**Comment by daniel-ciaglia** [comment]
As API tokens are deprecated, this is a required feature now ;-)
https://docs.getunleash.io/reference/api-tokens-and-client-keys#admin-tokens

> Deprecation Notice We do not recommend using admin tokens anymore, they are not connected to any user, and as such is a lot harder to track.
> For OSS and Pro users, we recommend using [Personal Access Tokens](https://docs.getunleash.io/reference/api-tokens-and-client-keys#personal-access-tokens) instead.
> Enterprise users have the option to use [Service accounts](https://docs.getunleash.io/reference/service-accounts).

**Comment by sighphyre** [comment]
This got added in the recent 1.3 release. I'm going to close this ticket
