### ISSUE TITLE
Allow setting auth token with an env variable prefixed with UNLEASH_

### ISSUE THREAD

**Issue by JonasBak** [Unleash/terraform-provider-unleash#90]
### Describe the feature request

I see that it is possible to provide the auth token using an environment variable called `AUTH_TOKEN`: https://github.com/Unleash/terraform-provider-unleash/blob/fbc8c70c98eeb6aaf09b5ec33af5d3150497acfe/internal/provider/provider.go#L50

I would really prefer if this was prefixed with `UNLEASH_`, as we use a lot of providers, and `AUTH_TOKEN` is very generic.
I know I could use a variable, but I prefer using env variables.

It would also be nice to have this feature documented: https://registry.terraform.io/providers/Unleash/unleash/latest/docs

**Comment by thomasheartman** [comment]
Hi, @JonasBak 👋🏼  Thanks for opening the issue. I agree, `UNLEASH_AUTH_TOKEN` would be less likely to conflict with anything else.

@gastonfournier Do you have any thoughts on this?

As for the docs, yeah, I think that's sensible. I'll try and see to it that it gets done.
