### ISSUE TITLE
Apply crashes on unleash_user when attempting to change value of send_email after import

### ISSUE THREAD

**Issue by JonasBak** [Unleash/terraform-provider-unleash#92]
### Describe the bug

I imported some users that were created manually. The resource definition looks like this:

```terraform
resource "unleash_user" "default" {
  for_each   = local.unleash_users
  email      = each.key
  name       = data.azuread_user.default[each.key].display_name
  root_role  = contains(local.unleash_users_admins, each.key) ? data.unleash_role.admin.id : data.unleash_role.viewer.id
  send_email = false
}
```

The next time I ran apply, it wanted to add the `send_email` field, as it was not set in the state. When running apply, I got the following error:
> Error: Provider produced inconsistent result after apply
> When applying changes to unleash_user.default["<USER_EMAIL>"], provider "provider[\"registry.terraform.io/unleash/unleash\"]" produced an unexpected new value: .send_email: was cty.False, but now null.
> This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to reproduce the bug

1. Define a `unleash_user` resource block that sets `send_email`
2. Import an existing user
3. Run apply

### Expected behavior

I don't expect the change in the `send_email` to actually do anything, as the user is already created, but I would expect the state to be updated and for the apply to not error.

### Logs, error output, etc.

```bash
Error: Provider produced inconsistent result after apply
When applying changes to unleash_user.default["<USER_EMAIL>"], provider "provider[\"registry.terraform.io/unleash/unleash\"]" produced an unexpected new value: .send_email: was cty.False, but now null.
This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Additional context

Workaround is to just ignore the changes to the field using:
```
  lifecycle {
    ignore_changes = [
      send_email,
    ]
  }
```

### Subscription type

None

### Hosting type

None

### SDK information (language and version)

 terraform-provider-unleash v1.0.3

**Comment by gastonfournier** [comment]
Just validated the issue agaianst 1.0.3, but after upgrading to `version = "1.1.0"` and running `terraform init -upgrade` I can now run `terraform apply`. I'm closing for now but do let me know if you still find issues with the import.
